name: Upload to Figshare
on: [push]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: figshare/github-upload-action@v1.1
        with:
          FIGSHARE_TOKEN: '80d7c78db83277e0ed744cf3cc025fc89fa3ccd570c504dc3a186ab3a03ee6f591fa7ed09c002d2d23a2a7e9b3ca68067ca86023cbf527b6b3c8e07ea1597262' 
          FIGSHARE_ENDPOINT: 'https://api.figshare.com/v2'
          FIGSHARE_ARTICLE_ID: 16538568 
          DATA_DIR: '.'
